do_test: True #boolean flag to run inference, False means no testing at all

type: "blind"

name: "tester_blind_bwe" #same as the file name, try to do that for all testers

#callable: 'testing.blind_bwe_tester.BlindTester'
#callable: 'testing.blind_bwe_tester.BlindTester'
callable: 'testing.piano_evaluator.Evaluator'
sampler_callable: 'testing.blind_bwe_sampler_BABE.BlindSampler'

#modes: ['unconditional', 'bwe', 'inpainting'] #modes to test
#modes: ['unconditional_operator','blind_bwe','unconditional', 'bwe'] #modes to test
#modes: ['unconditional_operator','filter_bwe'] #modes to test
#modes: ['unconditional','real_blind_bwe_complete','blind_bwe','real_blind_bwe','bwe'] #modes to test
#modes: ['unconditional','bwe','blind_bwe','real_blind_bwe'] #modes to test

#modes: ['single_example'] #modes to test
modes: ['multiple_recordings'] #modes to test
#modes: ['real_blind_bwe'] #modes to test
#modes: ['informed_bwe_BABE2'] #modes to test
#modes: ['blind_bwe_BABE2'] #modes to test
#modes: ['distorted_bwe'] #modes to test
#modes: ['bwe','blind_bwe'] #modes to test
#modes: ['unconditional_operator', 'filter_bwe'] #modes to test
T: 51  #number of discretizatio steprs
#T: 70 #number of discretizatio steprs
order: 2 #order of the discretization TODO: implement higher order samplers as the one used in ediffi

filter_out_cqt_DC_Nyq: True

#checkpoint: "testing_training_code-400000.pt"
checkpoint: "weights-489999.pt"
load_lora: False
base_checkpoint: None


#checkpoint_operator: "train_filters_diffusion_larger-250000.pt"

evaluation:
  path_dataset: "/scratch/elec/t412-asp/audio_datasets/archive_piano/historical_piano_50"
  single_recording: "78_1-mazurka-in-a-flat-major-op-59-no-2-2-mazurka-in-c-major-op-68-no-1_ar_gbia0226690a/1. MAZURKA IN A FLAT MAJOR (Op. 59, No. - Artur Rubinstein.flac_denoised.wav"
  start_s: [30,] #in seconds
  segment_length: 184184 #in samples
  num_segments_batch: 1
  segment_placement: "middle" #random, middle or start_s
  csv_file: "piano_recordings.csv" #for multiple recordings mode
  num_recordings: 1 
  process_complete_mode: "AR_blind_and_complete"
  overlap: 0.1


unconditional:
  num_samples: 8
  audio_len: 184184

posterior_sampling:
  xi: 0.2 # ) (between 0.4 and 0.8a for l2_sum)
  #xi: 0.5 # ) (between 0.4 and 0.8a for l2_sum)
  lr: 0.1
  #rec_distance: "l2_mean" #or "multiresSTFT"
  rec_distance: "l2_sum" #or "multiresSTFT"
  rec_distance_operator: "l2_hp" #or "multiresSTFT"
  prior_distance: "RED" #or "multiresSTFT"
  weight_rec_loss: 1 #use 0.00005 for multi-res STFT
  weight_rec_loss_operator: 1 #use 0.00005 for multi-res STFT
  annealing_y:
    use: False
    mode: "fixed"
    #mode: "fixed"
    sigma_min: 0.25
  multibatch:
    n_batch: 1
  grad_clipping: False
  clip_value: 0.5
  data_consistency: False #always False for blind bwe
  compensate_transition: True
  stft_distance:
    mag: False
    use: False
    use_multires: False
    nfft: 2048
  norm: 2  #"smoothl1" #1 or 2 or "smoothl1"
  smoothl1_beta: 1
  SNR_observations: "None"  #adding noise helps to stabilize the inference
  #sigma_observations: 0.01 #adding noise is critical!
  sigma_observations: None #adding noise is critical!
  start_sigma: 0.2
  freq_weighting: "None"
  freq_weighting_filter: "sqrt"
  normalization: "grad_norm"

#new diffusion parameters (only for sampling):
diff_params:
  same_as_training: False
  sigma_data: 0.063 #default for maestro
  sigma_min: 1e-4
  sigma_max: 1
  P_mean: -1.2 #what is this for?
  P_std: 1.2 #ehat is this for?
  ro: 8
  ro_train: 13
  Schurn: 20
  Snoise: 1.000
  Stmin: 0
  Stmax: 50

initialization:
  type: "zeros"
  sigma_init: 0.01

autoregressive:
  overlap: 0.25
  num_samples: 4

sampler: "stochastic" #wether deterministic or stochastic, unused as Scurn defineds the stochasticity

bandwidth_extension:
  sigma_observations: 0.00 #adding noise is critical!
  #start_sigma: "None" #this is the initial noise level, applied to the observations as the first step of the inference, "None" means start from sigma_max

  gain_boost: 0 #db boost to the gain of the audio signal

  test_filter_fit: False #testing fitting for blind bwe experiments
  compute_sweep: False #also logging stuff for blind bwe experiments
  decimate:
    factor: 1
  filter:
    type: "firwin" #or "cheby1_fir"
    fc: 1000 #cutoff frequency of the applied lpf
    order: 500
    fir_order: 500
    beta: 1
    ripple: 0.05 #for the cheby1
    resample:
      fs: 2000
    biquad:
      Q: 0.707

inpainting:
  gap_length: 1000 #in ms
  start_gap_idx: None #in ms, None means at the middle
comp_sens: 
  percentage: 5 #%
phase_retrieval:
  win_size: 1024
  hop_size: 256
max_thresh_grads: 1
type_spec: "linear" #or "mel" for phase retrieval
declipping:
  SDR: 3 #in dB

       
real_informed_bwe:
  filter:
    fc: [2500, 4000]
    A: [-40, -45]
  apply_filter_in_observations: False #WARNING set to False

#REDdiff_schedule:
#  type: "monotonic_log"
#  ro: 10
REDdiff_schedule:
  type: "multiepoch_monotonic_log"
  ro: 10
  num_epochs: 2


distortion:
  distortion_type: "tanh"
  drive_db: 30

blind_bwe: #this involves generative model of filters
  #num_slopes: 1
  lr_filter: 10
  num_x_updates_per_step: 1
  num_filter_updates_per_step: 100
  beta_eps: 0 #part of the noise that is deterministic
  weight_decay: 0
  clip_grad_norm: 1

  gain_boost: 0 #db boost to the gain of the audio signal
  sigma_norm: 0.07
  #LTAS:               
  #  sample_rate: 44100
  #  audio_len: 368368
  #  path: "/scratch/work/molinee2/datasets/MAESTRO/LTAS_MAESTRO.pt"
  real_recordings:
    path: /scratch/work/molinee2/projects/ddpm/blind_bwe_diffusion/audio_examples/samples_listening_test_real/the_chosen_ones
    num_samples: 8
  #SNR_observations: 50
  #sigma_observations: 0.01 #adding noise is critical!
  SNR_observations: None #adding noise is critical!
  compute_sweep: False #also logging stuff for blind bwe experiments
  Gain:
    optimize_G: False

  fcmin: 11 #or a number
  fcmax: "nyquist" #or a number
  Amin: -50
  Amax: 30
  Alim: 80
  NFFT: 4096
  sigma_den_estimate: 0.000 #this is the noise level of the observations, used for regularization
  test_filter:
    fref: 900
    fc_p: [1000, 3000]
    A_p: [0, -20, -30]
    fc_m: [700, 100]
    A_m: [0, 0, 0]
  initial_conditions:
    fc: [280,285,290,295,300]
    A: [-15,-17,-20,-25,-30]
  optimization: 
    #backtracking_enabled: True
    max_iter: 100
    grad_clip: 1
    #alpha: 0.2
    #beta: 0.5
    tol: [5e-3, 5e-3]
    mu: [1000, 10]
    #lr: 10
    #weights: [10, 0.1]
    clamp_fc: True
    clamp_A: True
    block_low_freq: False
    only_negative_A: True
    last_slope_fixed: True #if True, the last slope of A_p is fixed to -40dB/oct
    first_slope_fixed: True #if True, the last slope of A_m is fixed to 40dB/oct
       
collapse_regularization:
  use: False
  beta: 0.1 #the smaller the fatter the loss, so more regularization
  gamma: 1
  lambda_reg: 10 #this is the weight of the regularization term (the cost is normalized between 0 and 1)


denoiser:
  callable: 'networks.denoiser.MultiStage_denoise'
  checkpoint: '/scratch/work/molinee2/projects/ddpm/blind_bwe_diffusion/experiments_denoiser/pretrained_model/checkpoint_denoiser'
  sample_rate_denoiser: 22050
  segment_size: 5 #in seconds
  activation: "elu"
  use_csff: False
  use_SAM: True
  use_cam: False
  use_fam: False
  use_fencoding: True
  use_tdf: False
  use_alttdfs: False
  num_tfc: 3
  num_stages: 2
  depth: 6
  f_dim: 513 #hardcoded, depends on the stft window
  stft_win_size: 1024
  stft_hop_size: 256

   
complete_recording:
  #path: /scratch/work/molinee2/datasets/denoised_recordings/piano/ETUDE_IN_GES-DUR_(Schwarze-Tasten-_-_Ignace_Jan_Paderewski_denoised.wav
  #path: /scratch/work/molinee2/datasets/denoised_recordings/piano/2nd_Movement-Adagio_cantabile_-_WILHELM_BACKHAUS_denoised.wav
  #path: /scratch/work/molinee2/datasets/denoised_recordings/piano/Etude_in_F_Minor_-_Sergei_Rachmaninoff_-_E._Donagnyi_denoised.wav
  #path: /scratch/work/molinee2/datasets/denoised_recordings/piano/Etude_in_G_Sharp_Minor_-_Ignace_Jan_Paderewski_denoised.wav
  #path: /scratch/work/molinee2/datasets/denoised_recordings/piano/Etude_in_G_Sharp_Minor_-_Ignace_Jan_Paderewski_denoised.wav
  #path: /scratch/work/molinee2/datasets/denoised_recordings/piano/78_humoresque_felix-arndt-dvorak_gbia0013579a/Humoresque_-_Felix_Arndt_-_Dvorak_denoised.wav
  #=path: /scratch/work/molinee2/datasets/denoised_recordings/piano/78_etude-in-g-sharp-minor_ignace-jan-paderewski-chopin_gbia0183841b/Etude_in_G_Sharp_Minor_-_Ignace_Jan_Paderewski_noisy_input.wav
  #path: /scratch/work/molinee2/datasets/vocal_restoration/complete_recording/RAI-GramophoneGC-83600-01-1-001a_denoised_lpf_piano.wav
  #path: /scratch/work/molinee2/datasets/vocal_restoration/RAI-GramophoneGC-83600-01-1-001/piano.wav
  #path: /scratch/work/molinee2/datasets/vocal_restoration/WCD-008_17/piano.wav
  #path: /scratch/work/molinee2/datasets/vocal_restoration/WCD-027_25/piano.wav
  #path: /scratch/work/molinee2/datasets/vocal_restoration/WCD-008_09/piano.wav
  #path: /scratch/work/molinee2/datasets/vocal_restoration/WCD-027_27/piano.wav
  path: /scratch/work/molinee2/datasets/vocal_restoration/WCD-008_03/piano.wav

  #path: /scratch/work/molinee2/datasets/denoised_recordings/piano/78_impromptu-in-a-flat_harold-bauer-chopin_gbia0191066b/Impromptu_in_A_Flat_-_Harold_Bauer_-_Chopin_denoised.wav
  #path: /scratch/work/molinee2/datasets/denoised_recordings/piano/78_2nd-movement-adagio-cantabile_wilhelm-backhaus-beethoven_gbia7003781a/2nd_Movement-Adagio_cantabile_-_WILHELM_BACKHAUS_noisy_input.wav

  #path: /scratch/work/molinee3/datasets/denoised_recordings/piano/1._PRELUDE_IN_E_MINOR_(Opus_8,_No._4);_2._P_-_MARY_HALLOCK_denoised.wav
  #path: /scratch/work/molinee2/datasets/denoised_recordings/piano/78_1-prelude-in-e-minor-opus-8-no-4-2-prelude-in-c-minor-opus-28-no-4-3-p_gbia0276253a/1._PRELUDE_IN_E_MINOR_(Opus_8,_No._4);_2._P_-_MARY_HALLOCK_noisy_input.wav
  #path: /scratch/work/molinee2/datasets/denoised_recordings/piano/78_etude-in-f-minor_sergei-rachmaninoff-e-donagnyi_gbia0187069a/Etude_in_F_Minor_-_Sergei_Rachmaninoff_-_E._Donagnyi_denoised.wav
  #path: /scratch/work/molinee2/datasets/denoised_recordings/piano/78_etude-in-f-minor_sergei-rachmaninoff-e-donagnyi_gbia0187069a/Etude_in_F_Minor_-_Sergei_Rachmaninoff_-_E._Donagnyi_noisy_input.wav
  #path: /scratch/work/molinee2/datasets/denoised_recordings/piano/78_etude-in-f-minor_sergei-rachmaninoff-e-donagnyi_gbia0187069a/Etude_in_F_Minor_-_Sergei_Rachmaninoff_-_E._Donagnyi_noisy_input.wav
  use_denoiser: False
  SNR_extra_noise: "None"
  n_segments_blindstep: 2
  ix_start: 12 #in seconds
  std: 0.1 #normalizationout level 
  overlap: 0.25 #in seconds
  inpaint_DC: False #use data consistency for inpainting (not tested yet)
  inpaint_RG: True #use restoration guidance for inpainting (no extra cost as RG is already used for BWE) 
wandb:
  use: False
  entity: "eloimoliner"
  project: "blind_restoration"
  run_name: "fc_A"
  heavy_log_interval: 10
